version: "3"
services:
  app:
    build:
      context: .
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    links:
      - dynamodb
    depends_on:
      - dynamodb
  dynamodb:
    image: amazon/dynamodb-local:1.12.0
    container_name: dynamodb
    hostname: dynamodb
    ports:
      - "8042:8000"
